name: Test

on: [push, pull_request]

jobs:

  test:

    runs-on: ubuntu-latest

    steps:

    - uses: actions/setup-go@v2
      with:
        go-version: 1.18

    - uses: actions/checkout@v2

    - name: lint
      run: go run github.com/ysmood/golangci-lint@latest

    - name: test
      env:
        TERM: xterm-256color
      run: |
        go test -race -coverprofile=coverage.out ./...
        go run github.com/ysmood/got/cmd/check-cov@latest
